import {
  Activity,
  Anchor,
  Apple,
  Archive,
  Atom,
  Baby,
  ChartBar,
  ChartLine,
  ChartPie,
  Bone,
  BookOpen,
  Bookmark,
  Bot,
  Briefcase,
  Brush,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Car,
  ClipboardCheck,
  Clock,
  Cloud,
  Code,
  Coins,
  Compass,
  Cpu,
  Database,
  Dice5,
  Dna,
  Drama,
  Droplets,
  Dumbbell,
  Earth,
  Factory,
  Feather,
  FileText,
  Film,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Footprints,
  Gamepad2,
  Gavel,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  Headphones,
  Heart,
  HeartPulse,
  Highlighter,
  Hospital,
  Hourglass,
  Infinity as InfinityIcon,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  ListChecks,
  Lock,
  Magnet,
  Map as MapIcon,
  Megaphone,
  MessagesSquare,
  Mic,
  Microscope,
  Mountain,
  Music,
  Network,
  Newspaper,
  NotebookPen,
  NotepadText,
  Orbit,
  Palette,
  Paperclip,
  Pencil,
  PenTool,
  Percent,
  Pi,
  PiggyBank,
  Pill,
  Plane,
  Presentation,
  Puzzle,
  Quote,
  Recycle,
  Rocket,
  Ruler,
  Scale,
  Scroll,
  Server,
  Shapes,
  ShieldCheck,
  Ship,
  Sigma,
  Smartphone,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Target,
  Telescope,
  Terminal,
  Thermometer,
  TreePine,
  Trophy,
  Users,
  Utensils,
  Video,
  Vote,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon
} from "lucide-react";

export type IconChoice = { key: string; label: string; Icon: LucideIcon };
export type IconGroup = { name: string; icons: IconChoice[] };

export const iconGroups: IconGroup[] = [
  {
    name: "Study",
    icons: [
      { key: "book", label: "Book", Icon: BookOpen },
      { key: "notebook", label: "Notebook", Icon: NotebookPen },
      { key: "notes", label: "Notes", Icon: NotepadText },
      { key: "bookmark", label: "Bookmark", Icon: Bookmark },
      { key: "graduation", label: "Graduation", Icon: GraduationCap },
      { key: "library", label: "Library", Icon: Library },
      { key: "lightbulb", label: "Idea", Icon: Lightbulb },
      { key: "target", label: "Goal", Icon: Target },
      { key: "flag", label: "Milestone", Icon: Flag },
      { key: "calendar", label: "Calendar", Icon: Calendar },
      { key: "clock", label: "Time", Icon: Clock },
      { key: "hourglass", label: "Deadline", Icon: Hourglass },
      { key: "checklist", label: "Checklist", Icon: ListChecks },
      { key: "assignment", label: "Assignment", Icon: ClipboardCheck },
      { key: "pencil", label: "Writing", Icon: Pencil },
      { key: "highlighter", label: "Highlighter", Icon: Highlighter },
      { key: "paperclip", label: "Attachment", Icon: Paperclip },
      { key: "folder", label: "Folder", Icon: Folder },
      { key: "archive", label: "Archive", Icon: Archive },
      { key: "document", label: "Document", Icon: FileText },
      { key: "presentation", label: "Lecture", Icon: Presentation },
      { key: "video", label: "Video", Icon: Video },
      { key: "discussion", label: "Discussion", Icon: MessagesSquare },
      { key: "group", label: "Group work", Icon: Users },
      { key: "trophy", label: "Achievement", Icon: Trophy },
      { key: "star", label: "Favourite", Icon: Star },
      { key: "puzzle", label: "Problem solving", Icon: Puzzle },
      { key: "quote", label: "Quote", Icon: Quote },
      { key: "glasses", label: "Reading", Icon: Glasses }
    ]
  },
  {
    name: "Science and maths",
    icons: [
      { key: "science", label: "Chemistry", Icon: FlaskConical },
      { key: "atom", label: "Physics", Icon: Atom },
      { key: "microscope", label: "Microscope", Icon: Microscope },
      { key: "dna", label: "Genetics", Icon: Dna },
      { key: "telescope", label: "Astronomy", Icon: Telescope },
      { key: "orbit", label: "Space", Icon: Orbit },
      { key: "magnet", label: "Magnetism", Icon: Magnet },
      { key: "electricity", label: "Electricity", Icon: Zap },
      { key: "thermometer", label: "Temperature", Icon: Thermometer },
      { key: "leaf", label: "Biology", Icon: Leaf },
      { key: "sprout", label: "Botany", Icon: Sprout },
      { key: "tree", label: "Ecology", Icon: TreePine },
      { key: "sigma", label: "Mathematics", Icon: Sigma },
      { key: "pi", label: "Geometry", Icon: Pi },
      { key: "calculator", label: "Calculator", Icon: Calculator },
      { key: "ruler", label: "Measurement", Icon: Ruler },
      { key: "shapes", label: "Shapes", Icon: Shapes },
      { key: "infinity", label: "Calculus", Icon: InfinityIcon },
      { key: "line-chart", label: "Statistics", Icon: ChartLine },
      { key: "bar-chart", label: "Data", Icon: ChartBar },
      { key: "pie-chart", label: "Proportions", Icon: ChartPie },
      { key: "percent", label: "Percentages", Icon: Percent }
    ]
  },
  {
    name: "Technology",
    icons: [
      { key: "code", label: "Programming", Icon: Code },
      { key: "terminal", label: "Command line", Icon: Terminal },
      { key: "cpu", label: "Hardware", Icon: Cpu },
      { key: "database", label: "Databases", Icon: Database },
      { key: "network", label: "Networking", Icon: Network },
      { key: "server", label: "Servers", Icon: Server },
      { key: "security", label: "Security", Icon: ShieldCheck },
      { key: "lock", label: "Privacy", Icon: Lock },
      { key: "wifi", label: "Wireless", Icon: Wifi },
      { key: "bot", label: "AI", Icon: Bot },
      { key: "smartphone", label: "Mobile", Icon: Smartphone },
      { key: "laptop", label: "Computing", Icon: Laptop },
      { key: "gamepad", label: "Games", Icon: Gamepad2 }
    ]
  },
  {
    name: "Health",
    icons: [
      { key: "stethoscope", label: "Medicine", Icon: Stethoscope },
      { key: "heart-pulse", label: "Cardiology", Icon: HeartPulse },
      { key: "pill", label: "Pharmacology", Icon: Pill },
      { key: "syringe", label: "Nursing", Icon: Syringe },
      { key: "bone", label: "Anatomy", Icon: Bone },
      { key: "hospital", label: "Hospital", Icon: Hospital },
      { key: "apple", label: "Nutrition", Icon: Apple },
      { key: "dumbbell", label: "Fitness", Icon: Dumbbell },
      { key: "activity", label: "Physiology", Icon: Activity },
      { key: "baby", label: "Child development", Icon: Baby },
      { key: "smile", label: "Wellbeing", Icon: Smile }
    ]
  },
  {
    name: "Society and business",
    icons: [
      { key: "landmark", label: "History and government", Icon: Landmark },
      { key: "scale", label: "Law", Icon: Scale },
      { key: "gavel", label: "Courts", Icon: Gavel },
      { key: "vote", label: "Politics", Icon: Vote },
      { key: "newspaper", label: "Journalism", Icon: Newspaper },
      { key: "scroll", label: "Ancient history", Icon: Scroll },
      { key: "briefcase", label: "Business", Icon: Briefcase },
      { key: "coins", label: "Finance", Icon: Coins },
      { key: "piggy-bank", label: "Economics", Icon: PiggyBank },
      { key: "building", label: "Organisations", Icon: Building2 },
      { key: "factory", label: "Industry", Icon: Factory },
      { key: "handshake", label: "Management", Icon: Handshake },
      { key: "megaphone", label: "Marketing", Icon: Megaphone }
    ]
  },
  {
    name: "Geography and the world",
    icons: [
      { key: "globe", label: "Globe", Icon: Globe },
      { key: "earth", label: "Earth", Icon: Earth },
      { key: "map", label: "Geography", Icon: MapIcon },
      { key: "compass", label: "Navigation", Icon: Compass },
      { key: "mountain", label: "Geology", Icon: Mountain },
      { key: "sun", label: "Climate", Icon: Sun },
      { key: "cloud", label: "Weather", Icon: Cloud },
      { key: "droplets", label: "Water", Icon: Droplets },
      { key: "flame", label: "Energy", Icon: Flame },
      { key: "recycle", label: "Sustainability", Icon: Recycle },
      { key: "anchor", label: "Maritime", Icon: Anchor },
      { key: "ship", label: "Shipping", Icon: Ship },
      { key: "plane", label: "Aviation", Icon: Plane },
      { key: "car", label: "Transport", Icon: Car }
    ]
  },
  {
    name: "Arts and languages",
    icons: [
      { key: "art", label: "Art", Icon: Palette },
      { key: "brush", label: "Painting", Icon: Brush },
      { key: "design", label: "Design", Icon: PenTool },
      { key: "camera", label: "Photography", Icon: Camera },
      { key: "film", label: "Film", Icon: Film },
      { key: "music", label: "Music", Icon: Music },
      { key: "guitar", label: "Instruments", Icon: Guitar },
      { key: "mic", label: "Speaking", Icon: Mic },
      { key: "headphones", label: "Listening", Icon: Headphones },
      { key: "drama", label: "Drama", Icon: Drama },
      { key: "languages", label: "Languages", Icon: Languages },
      { key: "feather", label: "Literature", Icon: Feather }
    ]
  },
  {
    name: "Making and more",
    icons: [
      { key: "wrench", label: "Engineering", Icon: Wrench },
      { key: "hammer", label: "Construction", Icon: Hammer },
      { key: "rocket", label: "Launch", Icon: Rocket },
      { key: "utensils", label: "Cooking", Icon: Utensils },
      { key: "dice", label: "Probability", Icon: Dice5 },
      { key: "footprints", label: "Fieldwork", Icon: Footprints },
      { key: "sparkles", label: "Highlights", Icon: Sparkles },
      { key: "heart", label: "Personal", Icon: Heart }
    ]
  }
];

export const iconChoices = new Map(iconGroups.flatMap(({ icons }) => icons.map((choice) => [choice.key, choice])));
