export default function AboutPage() {
  return (
    <main className="mx-auto max-w-md px-4 py-16 text-sm text-ink/70">
      <h1 className="mb-2 text-lg font-semibold text-ink">
        About this scaffold
      </h1>
      <p>
        This is a starter generated by <code className="font-mono">chain init</code> — Tauri + React
        + TypeScript, with Tailwind CSS and basic routing (react-router-dom) already wired, plus the
        Chain SDK linked so <code className="font-mono">desktop.*</code> capabilities are ready to
        call.
      </p>
      <p className="mt-3">
        Replace this page, add real routes, and build your app. See{" "}
        <code className="font-mono">AGENTS.md</code> for what this scaffold does and doesn't
        include.
      </p>
    </main>
  );
}
