import type { Migration } from "@chain/sdk";

// Generated by `chain migration add recordings` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const recordings: Migration = {
  version: 16,
  name: "recordings",
  sql: `BEGIN;

CREATE TABLE "recording" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "page_id" INTEGER NOT NULL REFERENCES "page" ("id") ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "file_reference" TEXT NOT NULL,
  "mime_type" TEXT NOT NULL,
  "duration_ms" INTEGER NOT NULL,
  "transcript" TEXT,
  "segments" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX "recording_page" ON "recording" ("page_id");

COMMIT;`,
  down: `BEGIN;

DROP TABLE "recording";

COMMIT;`
};
