import type { Migration } from "@chain/sdk";

// Generated by `chain migration add page-audio` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const pageAudio: Migration = {
  version: 18,
  name: "page-audio",
  sql: `BEGIN;

CREATE TABLE "page_audio" (
  "page_id" INTEGER PRIMARY KEY REFERENCES "page" ("id") ON DELETE CASCADE,
  "file_reference" TEXT NOT NULL,
  "duration_ms" INTEGER NOT NULL,
  "voice_id" TEXT NOT NULL,
  "voice_name" TEXT NOT NULL,
  "speed" REAL NOT NULL,
  "sentences" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

COMMIT;`,
  down: `BEGIN;

DROP TABLE "page_audio";

COMMIT;`,
};
