import type { Migration } from "@chain/sdk";

// Generated by `chain migration add course-details` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const courseDetails: Migration = {
  version: 19,
  name: "course-details",
  sql: `BEGIN;

ALTER TABLE "course" ADD COLUMN "cover" TEXT;

ALTER TABLE "course" ADD COLUMN "position" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "course" ADD COLUMN "code" TEXT;

ALTER TABLE "course" ADD COLUMN "semester" TEXT;

ALTER TABLE "course" ADD COLUMN "school" TEXT;

ALTER TABLE "course" ADD COLUMN "instructor" TEXT;

COMMIT;`,
  down: `BEGIN;

ALTER TABLE "course" DROP COLUMN "cover";

ALTER TABLE "course" DROP COLUMN "position";

ALTER TABLE "course" DROP COLUMN "code";

ALTER TABLE "course" DROP COLUMN "semester";

ALTER TABLE "course" DROP COLUMN "school";

ALTER TABLE "course" DROP COLUMN "instructor";

COMMIT;`,
};
