import type { Migration } from "@chain/sdk";

// Generated by `chain migration add module-icon-and-order` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const moduleIconAndOrder: Migration = {
  version: 20,
  name: "module-icon-and-order",
  sql: `BEGIN;

ALTER TABLE "module" ADD COLUMN "icon" TEXT;

ALTER TABLE "module" ADD COLUMN "position" INTEGER NOT NULL DEFAULT 0;

COMMIT;`,
  down: `BEGIN;

ALTER TABLE "module" DROP COLUMN "icon";

ALTER TABLE "module" DROP COLUMN "position";

COMMIT;`,
};
