import type { Migration } from "@chain/sdk";

// Generated by `chain migration add page-icon-cover-order` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const pageIconCoverOrder: Migration = {
  version: 21,
  name: "page-icon-cover-order",
  sql: `BEGIN;

ALTER TABLE "page" ADD COLUMN "icon" TEXT;

ALTER TABLE "page" ADD COLUMN "cover" TEXT;

ALTER TABLE "page" ADD COLUMN "position" INTEGER NOT NULL DEFAULT 0;

COMMIT;`,
  down: `BEGIN;

ALTER TABLE "page" DROP COLUMN "icon";

ALTER TABLE "page" DROP COLUMN "cover";

ALTER TABLE "page" DROP COLUMN "position";

COMMIT;`,
};
