import type { Migration } from "@chain/sdk";

// Generated by `chain migration add attachment-size` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const attachmentSize: Migration = {
  version: 22,
  name: "attachment-size",
  sql: `BEGIN;

ALTER TABLE "attachment" ADD COLUMN "size_bytes" INTEGER;

COMMIT;`,
  down: `BEGIN;

ALTER TABLE "attachment" DROP COLUMN "size_bytes";

COMMIT;`,
};
