import type { Migration } from "@chain/sdk";

// Generated by `chain migration add page-opened-at` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const pageOpenedAt: Migration = {
  version: 23,
  name: "page-opened-at",
  sql: `BEGIN;

ALTER TABLE "page" ADD COLUMN "opened_at" TEXT;

COMMIT;`,
  down: `BEGIN;

ALTER TABLE "page" DROP COLUMN "opened_at";

COMMIT;`,
};
