import type { Migration } from "@chain/sdk";

// Generated by `chain migration add home-widgets` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const homeWidgets: Migration = {
  version: 24,
  name: "home-widgets",
  sql: `BEGIN;

CREATE TABLE "home_widget" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "kind" TEXT NOT NULL,
  "size" TEXT NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "config" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE "study_day" (
  "day" TEXT PRIMARY KEY NOT NULL,
  "opened" INTEGER NOT NULL DEFAULT 0,
  "completed" INTEGER NOT NULL DEFAULT 0
);

COMMIT;`,
  down: `BEGIN;

DROP TABLE "home_widget";

DROP TABLE "study_day";

COMMIT;`,
};
