import type { Migration } from "@chain/sdk";

// Generated by `chain migration add record-timestamps` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const recordTimestamps: Migration = {
  version: 25,
  name: "record-timestamps",
  sql: `BEGIN;

-- Rebuild "attachment" (add updated_at): SQLite can't do this with ALTER TABLE.

CREATE TABLE "__chain_new_attachment" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "page_id" INTEGER NOT NULL,
  "file_name" TEXT NOT NULL,
  "file_path" TEXT NOT NULL,
  "mime_type" TEXT,
  "size_bytes" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO "__chain_new_attachment" ("id", "page_id", "file_name", "file_path", "mime_type", "size_bytes", "created_at")
  SELECT "id", "page_id", "file_name", "file_path", "mime_type", "size_bytes", "created_at" FROM "attachment";

DROP TABLE "attachment";

PRAGMA legacy_alter_table = ON;

ALTER TABLE "__chain_new_attachment" RENAME TO "attachment";

PRAGMA legacy_alter_table = OFF;

-- Rebuild "settings" (add created_at, add updated_at): SQLite can't do this with ALTER TABLE.

CREATE TABLE "__chain_new_settings" (
  "key" TEXT PRIMARY KEY,
  "value" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO "__chain_new_settings" ("key", "value")
  SELECT "key", "value" FROM "settings";

DROP TABLE "settings";

PRAGMA legacy_alter_table = ON;

ALTER TABLE "__chain_new_settings" RENAME TO "settings";

PRAGMA legacy_alter_table = OFF;

COMMIT;`,
  down: `BEGIN;

ALTER TABLE "attachment" DROP COLUMN "updated_at";

ALTER TABLE "settings" DROP COLUMN "created_at";

ALTER TABLE "settings" DROP COLUMN "updated_at";

COMMIT;`,
};
