import type { Migration } from "@chain/sdk";

// Generated by `chain migration add recently-deleted` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const recentlyDeleted: Migration = {
  version: 26,
  name: "recently-deleted",
  sql: `BEGIN;

ALTER TABLE "course" ADD COLUMN "deleted_at" TEXT;

ALTER TABLE "module" ADD COLUMN "deleted_at" TEXT;

ALTER TABLE "page" ADD COLUMN "deleted_at" TEXT;

COMMIT;`,
  down: `BEGIN;

ALTER TABLE "course" DROP COLUMN "deleted_at";

ALTER TABLE "module" DROP COLUMN "deleted_at";

ALTER TABLE "page" DROP COLUMN "deleted_at";

COMMIT;`,
};
