import type { Migration } from "@chain/sdk";

// Generated by `chain migration add main-link-indexes` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const mainLinkIndexes: Migration = {
  version: 27,
  name: "main-link-indexes",
  sql: `BEGIN;

CREATE INDEX "attachment_page" ON "attachment" ("page_id");

CREATE INDEX "module_course" ON "module" ("course_id");

CREATE INDEX "page_module" ON "page" ("module_id");

COMMIT;`,
  down: `BEGIN;

DROP INDEX "attachment_page";

DROP INDEX "module_course";

DROP INDEX "page_module";

COMMIT;`,
};
