import type { Migration } from "@chain/sdk";

// Generated by `chain migration add usage-indexes` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const usageIndexes: Migration = {
  version: 28,
  name: "usage-indexes",
  sql: `BEGIN;

CREATE INDEX "agent_usage_invoked" ON "agent_usage" ("invoked_at");

CREATE INDEX "course_ai_profile" ON "course" ("ai_profile_id");

CREATE INDEX "highlight_created" ON "highlight" ("created_at");

CREATE INDEX "module_deleted" ON "module" ("deleted_at") WHERE deleted_at IS NOT NULL;

CREATE INDEX "page_created" ON "page" ("created_at");

CREATE INDEX "page_deleted" ON "page" ("deleted_at") WHERE deleted_at IS NOT NULL;

CREATE INDEX "page_updated" ON "page" ("updated_at");

CREATE INDEX "recording_created" ON "recording" ("created_at");

COMMIT;`,
  down: `BEGIN;

DROP INDEX "agent_usage_invoked";

DROP INDEX "course_ai_profile";

DROP INDEX "highlight_created";

DROP INDEX "module_deleted";

DROP INDEX "page_created";

DROP INDEX "page_deleted";

DROP INDEX "page_updated";

DROP INDEX "recording_created";

COMMIT;`,
};
