import type { Migration } from "@chain/sdk";

// Generated by `chain migration add page-opened-index` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const pageOpenedIndex: Migration = {
  version: 29,
  name: "page-opened-index",
  sql: `BEGIN;

UPDATE page SET opened_at = updated_at WHERE opened_at IS NULL;

CREATE INDEX "page_opened" ON "page" ("opened_at");

CREATE TRIGGER page_opened_on_insert AFTER INSERT ON page WHEN NEW.opened_at IS NULL BEGIN
      UPDATE page SET opened_at = NEW.updated_at WHERE id = NEW.id;
    END;

COMMIT;`,
  down: `BEGIN;

DROP TRIGGER "page_opened_on_insert";

DROP INDEX "page_opened";

COMMIT;`,
};
