import type { Migration } from "@chain/sdk";

// Generated by `chain migration add home-layouts` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const homeLayouts: Migration = {
  version: 30,
  name: "home-layouts",
  sql: `BEGIN;

CREATE TABLE "home_layout" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "widgets" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX "home_layout_name" ON "home_layout" ("name");

COMMIT;`,
  down: `BEGIN;

DROP TABLE "home_layout";

COMMIT;`,
};
