import type { Migration } from "@chain/sdk";

// Generated by `chain migration add action-packs` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const actionPacks: Migration = {
  version: 31,
  name: "action-packs",
  sql: `BEGIN;

CREATE TABLE "action_pack" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "catalog_key" TEXT,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL DEFAULT '',
  "area" INTEGER,
  "installed_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX "action_pack_catalog_key" ON "action_pack" ("catalog_key");

CREATE TRIGGER action_pack_delete BEFORE DELETE ON action_pack BEGIN
      DELETE FROM ai_action WHERE pack_id = OLD.id;
    END;

-- Rebuild "ai_action" (add pack_id, add enabled, change keys or constraints): SQLite can't do this with ALTER TABLE.

CREATE TABLE "__chain_new_ai_action" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "prompt" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "position" INTEGER NOT NULL DEFAULT 0,
  "icon" TEXT,
  "scope" INTEGER NOT NULL DEFAULT 1,
  "output" INTEGER NOT NULL DEFAULT 1,
  "page_types" TEXT,
  "pack_id" INTEGER REFERENCES "action_pack" ("id") ON DELETE CASCADE,
  "enabled" INTEGER NOT NULL DEFAULT 1
);

INSERT INTO "__chain_new_ai_action" ("id", "name", "prompt", "created_at", "updated_at", "position", "icon", "scope", "output", "page_types")
  SELECT "id", "name", "prompt", "created_at", "updated_at", "position", "icon", "scope", "output", "page_types" FROM "ai_action";

DROP TABLE "ai_action";

PRAGMA legacy_alter_table = ON;

ALTER TABLE "__chain_new_ai_action" RENAME TO "ai_action";

PRAGMA legacy_alter_table = OFF;

CREATE INDEX "ai_action_pack" ON "ai_action" ("pack_id");

COMMIT;`,
  down: `BEGIN;

DROP TABLE "action_pack";

-- Rebuild "ai_action" (drop pack_id, drop enabled, change keys or constraints): SQLite can't do this with ALTER TABLE.

CREATE TABLE "__chain_new_ai_action" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "prompt" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "position" INTEGER NOT NULL DEFAULT 0,
  "icon" TEXT,
  "scope" INTEGER NOT NULL DEFAULT 1,
  "output" INTEGER NOT NULL DEFAULT 1,
  "page_types" TEXT
);

INSERT INTO "__chain_new_ai_action" ("id", "name", "prompt", "created_at", "updated_at", "position", "icon", "scope", "output", "page_types")
  SELECT "id", "name", "prompt", "created_at", "updated_at", "position", "icon", "scope", "output", "page_types" FROM "ai_action";

DROP TABLE "ai_action";

PRAGMA legacy_alter_table = ON;

ALTER TABLE "__chain_new_ai_action" RENAME TO "ai_action";

PRAGMA legacy_alter_table = OFF;

COMMIT;`,
};
