import type { Migration } from "@chain/sdk";

// Generated by `chain migration add unfiled-recordings` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const unfiledRecordings: Migration = {
  version: 32,
  name: "unfiled-recordings",
  sql: `BEGIN;

-- Rebuild "recording" (change page_id): SQLite can't do this with ALTER TABLE.

CREATE TABLE "__chain_new_recording" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "page_id" INTEGER REFERENCES "page" ("id") ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "file_reference" TEXT NOT NULL,
  "mime_type" TEXT NOT NULL,
  "duration_ms" INTEGER NOT NULL,
  "transcript" TEXT,
  "segments" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO "__chain_new_recording" ("id", "page_id", "name", "file_reference", "mime_type", "duration_ms", "transcript", "segments", "created_at", "updated_at")
  SELECT "id", "page_id", "name", "file_reference", "mime_type", "duration_ms", "transcript", "segments", "created_at", "updated_at" FROM "recording";

DROP TABLE "recording";

PRAGMA legacy_alter_table = ON;

ALTER TABLE "__chain_new_recording" RENAME TO "recording";

PRAGMA legacy_alter_table = OFF;

CREATE INDEX "recording_created" ON "recording" ("created_at");

CREATE INDEX "recording_page" ON "recording" ("page_id");

COMMIT;`,
  down: `BEGIN;

-- Rebuild "recording" (change page_id): SQLite can't do this with ALTER TABLE.

CREATE TABLE "__chain_new_recording" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "page_id" INTEGER NOT NULL REFERENCES "page" ("id") ON DELETE CASCADE,
  "name" TEXT NOT NULL,
  "file_reference" TEXT NOT NULL,
  "mime_type" TEXT NOT NULL,
  "duration_ms" INTEGER NOT NULL,
  "transcript" TEXT,
  "segments" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

INSERT INTO "__chain_new_recording" ("id", "page_id", "name", "file_reference", "mime_type", "duration_ms", "transcript", "segments", "created_at", "updated_at")
  SELECT "id", COALESCE("page_id", 0), "name", "file_reference", "mime_type", "duration_ms", "transcript", "segments", "created_at", "updated_at" FROM "recording";

DROP TABLE "recording";

PRAGMA legacy_alter_table = ON;

ALTER TABLE "__chain_new_recording" RENAME TO "recording";

PRAGMA legacy_alter_table = OFF;

CREATE INDEX "recording_created" ON "recording" ("created_at");

CREATE INDEX "recording_page" ON "recording" ("page_id");

COMMIT;`,
};
