import type { Migration } from "@chain/sdk";

// Generated by `chain migration add conversation-mode` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const conversationMode: Migration = {
  version: 33,
  name: "conversation-mode",
  sql: `BEGIN;

ALTER TABLE "agent_conversation" ADD COLUMN "mode" INTEGER NOT NULL DEFAULT 1;

COMMIT;`,
  down: `BEGIN;

ALTER TABLE "agent_conversation" DROP COLUMN "mode";

COMMIT;`,
};
