import type { Migration } from "@chain/sdk";

// Generated by `chain migration add agent-activity` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const agentActivity: Migration = {
  version: 34,
  name: "agent-activity",
  sql: `BEGIN;

CREATE TABLE "agent_activity" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "conversation_id" INTEGER REFERENCES "agent_conversation" ("id") ON DELETE SET NULL,
  "tool" TEXT NOT NULL,
  "permission" INTEGER NOT NULL DEFAULT 1,
  "description" TEXT NOT NULL,
  "outcome" INTEGER NOT NULL,
  "detail" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX "agent_activity_conversation" ON "agent_activity" ("conversation_id");

CREATE INDEX "agent_activity_created" ON "agent_activity" ("created_at");

COMMIT;`,
  down: `BEGIN;

DROP TABLE "agent_activity";

COMMIT;`,
};
