import type { Migration } from "@chain/sdk";

// Generated by `chain migration add page-passages` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const pagePassages: Migration = {
  version: 35,
  name: "page-passages",
  sql: `BEGIN;

CREATE TABLE "page_passage" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "page_id" INTEGER NOT NULL,
  "position" INTEGER NOT NULL,
  "text" TEXT NOT NULL,
  "vector" TEXT NOT NULL,
  "model" TEXT NOT NULL,
  "source_updated_at" TEXT NOT NULL
);

CREATE INDEX "page_passage_model" ON "page_passage" ("model");

CREATE INDEX "page_passage_page" ON "page_passage" ("page_id");

COMMIT;`,
  down: `BEGIN;

DROP TABLE "page_passage";

COMMIT;`,
};
