import type { Migration } from "@chain/sdk";

// Generated by `chain migration add custom-page-types` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const customPageTypes: Migration = {
  version: 36,
  name: "custom-page-types",
  sql: `BEGIN;

CREATE TABLE "custom_page_type" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

COMMIT;`,
  down: `BEGIN;

DROP TABLE "custom_page_type";

COMMIT;`,
};
