import type { Migration } from "@chain/sdk";

// Generated by `chain migration add flashcards` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const flashcards: Migration = {
  version: 37,
  name: "flashcards",
  sql: `BEGIN;

CREATE TABLE "flashcard" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "module_id" INTEGER NOT NULL,
  "page_id" INTEGER,
  "front" TEXT NOT NULL,
  "back" TEXT NOT NULL,
  "ease" REAL NOT NULL DEFAULT 2.5,
  "interval_days" REAL NOT NULL DEFAULT 0,
  "repetitions" INTEGER NOT NULL DEFAULT 0,
  "due_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "right_count" INTEGER NOT NULL DEFAULT 0,
  "wrong_count" INTEGER NOT NULL DEFAULT 0,
  "last_reviewed_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX "flashcard_due" ON "flashcard" ("due_at");

CREATE INDEX "flashcard_module" ON "flashcard" ("module_id");

CREATE INDEX "flashcard_page" ON "flashcard" ("page_id");

COMMIT;`,
  down: `BEGIN;

DROP TABLE "flashcard";

COMMIT;`,
};
