import type { Migration } from "@chain/sdk";

// Generated by `chain migration add tasks` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const tasks: Migration = {
  version: 38,
  name: "tasks",
  sql: `BEGIN;

CREATE TABLE "task" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT NOT NULL,
  "type" INTEGER NOT NULL DEFAULT 5,
  "course_id" INTEGER,
  "module_id" INTEGER,
  "page_id" INTEGER,
  "due_on" TEXT,
  "completed_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX "task_course" ON "task" ("course_id");

CREATE INDEX "task_due" ON "task" ("due_on");

CREATE INDEX "task_module" ON "task" ("module_id");

COMMIT;`,
  down: `BEGIN;

DROP TABLE "task";

COMMIT;`,
};
