import type { Migration } from "@chain/sdk";

// Generated by `chain migration add quizzes` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const quizzes: Migration = {
  version: 39,
  name: "quizzes",
  sql: `BEGIN;

CREATE TABLE "quiz" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "module_id" INTEGER NOT NULL,
  "page_id" INTEGER,
  "title" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
  "updated_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX "quiz_module" ON "quiz" ("module_id");

CREATE TABLE "quiz_attempt" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "quiz_id" INTEGER NOT NULL,
  "score" INTEGER NOT NULL,
  "total" INTEGER NOT NULL,
  "answers" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX "quiz_attempt_quiz" ON "quiz_attempt" ("quiz_id");

CREATE TABLE "quiz_question" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "quiz_id" INTEGER NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "kind" INTEGER NOT NULL DEFAULT 1,
  "prompt" TEXT NOT NULL,
  "choices" TEXT,
  "answer" TEXT NOT NULL,
  "explanation" TEXT,
  "page_id" INTEGER
);

CREATE INDEX "quiz_question_quiz" ON "quiz_question" ("quiz_id");

COMMIT;`,
  down: `BEGIN;

DROP TABLE "quiz";

DROP TABLE "quiz_attempt";

DROP TABLE "quiz_question";

COMMIT;`,
};
