import type { Migration } from "@chain/sdk";

// Generated by `chain migration add study-sessions` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const studySessions: Migration = {
  version: 40,
  name: "study-sessions",
  sql: `BEGIN;

ALTER TABLE "quiz_question" ADD COLUMN "topic" TEXT;

CREATE TABLE "study_session" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "module_id" INTEGER NOT NULL,
  "quiz_id" INTEGER,
  "overview" TEXT NOT NULL,
  "topics" TEXT NOT NULL,
  "results" TEXT,
  "quiz_right" INTEGER,
  "quiz_total" INTEGER,
  "cards_right" INTEGER NOT NULL DEFAULT 0,
  "cards_wrong" INTEGER NOT NULL DEFAULT 0,
  "finished_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX "study_session_module" ON "study_session" ("module_id");

COMMIT;`,
  down: `BEGIN;

DROP TABLE "study_session";

ALTER TABLE "quiz_question" DROP COLUMN "topic";

COMMIT;`
};
