import type { Migration } from "@chain/sdk";

// Generated by `chain migration add module-prep` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const modulePrep: Migration = {
  version: 41,
  name: "module-prep",
  sql: `BEGIN;

CREATE TABLE "module_prep" (
  "module_id" INTEGER PRIMARY KEY,
  "topics" TEXT NOT NULL DEFAULT '[]',
  "summary_page_id" INTEGER,
  "notes_page_id" INTEGER,
  "quiz_id" INTEGER,
  "unread" TEXT NOT NULL DEFAULT '[]',
  "prepared_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE "page_digest" (
  "page_id" INTEGER PRIMARY KEY,
  "source_hash" TEXT NOT NULL,
  "digest" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (datetime('now'))
);

COMMIT;`,
  down: `BEGIN;

DROP TABLE "module_prep";

DROP TABLE "page_digest";

COMMIT;`
};
