import type { Migration } from "@chain/sdk";

// Generated by `chain migration add page-source` from the classes in ../schema.
// Never edit a migration once it has shipped; change the classes and add
// another. `down` is what `chain database update <earlier version>` runs.
export const pageSource: Migration = {
  version: 42,
  name: "page-source",
  sql: `BEGIN;

ALTER TABLE "page" ADD COLUMN "source" TEXT;

COMMIT;`,
  down: `BEGIN;

ALTER TABLE "page" DROP COLUMN "source";

COMMIT;`
};
