import type { Migration } from "@chain/sdk";
import { initial } from "./0001-initial.ts";
import { completionTracking } from "./0002-completion-tracking.ts";
import { numericEnums } from "./0003-numeric-enums.ts";
import { agentChat } from "./0004-agent-chat.ts";
import { widenAgentKind } from "./0005-widen-agent-kind.ts";
import { fixAgentConnectionFkReferences } from "./0006-fix-agent-connection-fk-references.ts";
import { agentConnectionModel } from "./0007-agent-connection-model.ts";
import { highlights } from "./0008-highlights.ts";
import { highlightHtml } from "./0009-highlight-html.ts";
import { highlightOrphaning } from "./0010-highlight-orphaning.ts";
import { aiActionDefaults } from "./0011-ai-action-defaults.ts";
import { customAiActions } from "./0012-custom-ai-actions.ts";
import { aiProfiles } from "./0013-ai-profiles.ts";
import { aiProfileSettings } from "./0014-ai-profile-settings.ts";
import { agentMessageAttachments } from "./0015-agent-message-attachments.ts";
import { recordings } from "./0016-recordings.ts";
import { cleanTranscriptAction } from "./0017-clean-transcript-action.ts";
import { pageAudio } from "./0018-page-audio.ts";
import { courseDetails } from "./0019-course-details.ts";
import { moduleIconAndOrder } from "./0020-module-icon-and-order.ts";
import { pageIconCoverOrder } from "./0021-page-icon-cover-order.ts";
import { attachmentSize } from "./0022-attachment-size.ts";
import { pageOpenedAt } from "./0023-page-opened-at.ts";
import { homeWidgets } from "./0024-home-widgets.ts";
import { recordTimestamps } from "./0025-record-timestamps.ts";
import { recentlyDeleted } from "./0026-recently-deleted.ts";
import { mainLinkIndexes } from "./0027-main-link-indexes.ts";
import { usageIndexes } from "./0028-usage-indexes.ts";
import { pageOpenedIndex } from "./0029-page-opened-index.ts";
import { homeLayouts } from "./0030-home-layouts.ts";
import { actionPacks } from "./0031-action-packs.ts";
import { unfiledRecordings } from "./0032-unfiled-recordings.ts";

// Generated by `chain migration` — oldest to newest. Never edit by hand.
// `desktop.storage.migrate` applies whichever versions haven't run yet,
// so this is safe to call on every app startup.
export const migrations: Migration[] = [
  initial,
  completionTracking,
  numericEnums,
  agentChat,
  widenAgentKind,
  fixAgentConnectionFkReferences,
  agentConnectionModel,
  highlights,
  highlightHtml,
  highlightOrphaning,
  aiActionDefaults,
  customAiActions,
  aiProfiles,
  aiProfileSettings,
  agentMessageAttachments,
  recordings,
  cleanTranscriptAction,
  pageAudio,
  courseDetails,
  moduleIconAndOrder,
  pageIconCoverOrder,
  attachmentSize,
  pageOpenedAt,
  homeWidgets,
  recordTimestamps,
  recentlyDeleted,
  mainLinkIndexes,
  usageIndexes,
  pageOpenedIndex,
  homeLayouts,
  actionPacks,
  unfiledRecordings,
];
