import type { Migration } from "@chain/sdk";
import { initial } from "./0001-initial.ts";
import { completionTracking } from "./0002-completion-tracking.ts";
import { numericEnums } from "./0003-numeric-enums.ts";
import { agentChat } from "./0004-agent-chat.ts";
import { widenAgentKind } from "./0005-widen-agent-kind.ts";
import { fixAgentConnectionFkReferences } from "./0006-fix-agent-connection-fk-references.ts";
import { agentConnectionModel } from "./0007-agent-connection-model.ts";
import { highlights } from "./0008-highlights.ts";
import { highlightHtml } from "./0009-highlight-html.ts";
import { highlightOrphaning } from "./0010-highlight-orphaning.ts";
import { aiActionDefaults } from "./0011-ai-action-defaults.ts";
import { customAiActions } from "./0012-custom-ai-actions.ts";
import { aiProfiles } from "./0013-ai-profiles.ts";
import { aiProfileSettings } from "./0014-ai-profile-settings.ts";
import { agentMessageAttachments } from "./0015-agent-message-attachments.ts";

// Generated by `chain migration` — oldest to newest. Never edit by hand.
// `desktop.storage.migrate` applies whichever versions haven't run yet,
// so this is safe to call on every app startup.
export const migrations: Migration[] = [
  initial,
  completionTracking,
  numericEnums,
  agentChat,
  widenAgentKind,
  fixAgentConnectionFkReferences,
  agentConnectionModel,
  highlights,
  highlightHtml,
  highlightOrphaning,
  aiActionDefaults,
  customAiActions,
  aiProfiles,
  aiProfileSettings,
  agentMessageAttachments,
];
