import type { Migration } from "@chain/sdk";
import { initial } from "./0001-initial.ts";
import { completionTracking } from "./0002-completion-tracking.ts";
import { numericEnums } from "./0003-numeric-enums.ts";

// Generated by `chain migration` — ordered oldest to newest, one file
// per version. Never edit a shipped migration in place; running
// `chain migration <name>` again adds the next one and regenerates this
// file. `desktop.storage.migrate` applies whichever versions haven't run
// yet, so this is safe to call on every app startup.
export const migrations: Migration[] = [
  initial,
  completionTracking,
  numericEnums,
];
